### ISSUE TITLE
Reading raw data from instrument

### ISSUE THREAD

**Issue by katyo** [KrisNK/rs-usbtmc#2]
Raw data which can be read using query like `:WAV:DATA?` may contains zero bytes but if I understand correctly the read function filter out such things:

https://github.com/KrisNK/rs-usbtmc/blob/6b3fb7a33eb4fde529d32a3370731546c4a57998/src/communication/bulk.rs#L134-L138

**Comment by KrisNK** [comment]
Hi Katyo, thank you for bringing this up. You are correct.

The purpose of filtering the data is to then parse it to a `String`, but I implemented it in the wrong function. I moved the filter to the `query` method of UsbtmcClient.

Thanks again and feel free to let me know if my solution can be improved.

**Comment by katyo** [comment]
@KrisNK What the reason to filter non-ascii and null bytes before converting responses to string? Are you have any instruments which returns such things? Other TMC libs which I seen does not do that at all.

I think it's enough to trim before converting to a string (i.e. remove null bytes at end).

**Comment by KrisNK** [comment]
@katyo You pointed out the exact reason. The oscilloscope I use, depending on the data I request, will send non-ASCII bytes. To be able to handle all kinds of requests, I made a query_raw method.

An example usage would be from coping an screen capture of the scope.

Thanks for the help! I'll close this issue.

**Comment by katyo** [comment]
@KrisNK 
I mean that instruments usually never sends non-ascii bytes in a textual responses.
So filtering such bytes seems a wrong behavior for me.

**Comment by KrisNK** [comment]
@katyo 

The filter is implemented differently than the first time. 

When sending messages, the packets must be a number of bytes long that is divisible by 4. If not, null bytes are added for padding. 

This new filter just removes the padding and removes non-ASCII bytes as a precaution. 

I'll keep filtering out the null bytes padding, but I agree that in a purely textual context removing non-ASCII bytes is unnecessary. 

My goal was to make sure nothing crashes if a user uses "query" in a non textual context where non-ASCII bytes are possible. However, creating an appropriate error is better. 

I'll find the time to get that done.
